apiVersion: v1
kind: Secret
metadata:
  name: postgres-cluster-auth
  namespace: quickwit
type: Opaque
stringData:
  superUserPassword: INSECURE_DEV_PASSWORD
  replicationUserPassword: INSECURE_DEV_PASSWORD
                    
