apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: quickwit

spec:

   replicas: 1
   image: docker.io/postgres:16.3

   database:
      storageClassName: csi-hostpath-sc
      size: 32Gi

   resources:
      requests:
         memory: "0"
         cpu: "0"
      limits:
         memory: "2Gi"
         cpu: "1"

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-cluster-auth
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgres-cluster-auth
              key: replicationUserPassword
