
image:
  repository: docker.io/quickwit/quickwit
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  #tag: v0.6.4

config:
  default_index_root_uri: s3://quickwit-dev/quickwit-indexes
  metastore_uri: postgres://postgres:INSECURE_DEV_PASSWORD@postgres.quickwit.svc.cluster.local:5432/quickwit-metastore

  storage:
    s3:
      flavor: minio
      region: default
      endpoint: http://minio.minio.svc.cluster.local:9000
      force_path_style_access: true
      access_key_id: "INSECURE_DEV_MINIO_ACCESS_KEY"
      secret_access_key: "INSECURE_DEV_MINIO_SECRET_KEY"

metastore:
  replicaCount: 1

searcher:
  replicaCount: 1
