apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
         app: docker-registry
    spec:
      containers:
        - name: registry
          image: registry:latest
          imagePullPolicy: Always
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Thorium
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /opt/htpasswd
          resources:
            requests:
              memory: "8Gi"
              cpu: "4"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - mountPath: "/opt/htpasswd"
              name: htpasswd
              subPath: htpasswd
            - mountPath: "/var/lib/registry"
              name: docker-registry-data
      volumes:
        - name: htpasswd
          secret:
            secretName: registry-passwd
        - name: registry-conf
          secret:
            secretName: registry-conf
        - name: docker-registry-data
          persistentVolumeClaim:
            claimName: registry-persistent-storage-claim 
