apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-persistent-storage-claim
spec:
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage: 12Ti
  accessModes:
      - ReadWriteOnce
