apiVersion: sandia.gov/v1
kind: ThoriumCluster
metadata:
  name: prod
  namespace: thorium
spec:
  registry: "<REGISTRY.DOMAIN/path/to/image/thorium>"
  version: "<IMAGE TAG>"
  image_pull_policy: Always
  components:
    api:
      replicas: 1
      urls:
      - "<THORIUM FQDN>"
      ports:
      - 80
      - 443
    scaler:
      service_account: true
    baremetal_scaler: {}
    search_streamer: {}
    event_handler: {}
  config: 
    thorium:
      secret_key: "<SECRET>" 
      tracing:
        external:
          Grpc:
            endpoint: "http://quickwit-indexer.quickwit.svc.cluster.local:7281"
            level: "Info"
        local:
          level: "Info"
      files:
        bucket: "thorium-files"
        password: "SecretCornIsBest"
        earliest: 1610596807
      results:
        bucket: "thorium-result-files"
        earliest: 1610596807
      attachments:
        bucket: "thorium-comment-files"
      repos:
        bucket: "thorium-repo-files"
      ephemeral:
        bucket: "thorium-ephemeral-files"
      s3:
        access_key: "<KEY>"
        secret_token: "<TOKEN>"
        endpoint: "https://<S3 FQDN>"
      auth:
        local_user_ids:
          group: 1879048192
          user: 1879048192
        token_expire: 90
      scaler:
        crane:
          insecure: true
        k8s:
          clusters:
            kubernetes-admin@cluster.local:
              alias: "production"
              nodes:
                - "<K8s host 1>"
                - "<K8s host 2>"
                - "<K8s host 3>"
                - "<K8s host 4>"
                - "<K8s host 5>"
    redis:
      host: "redis.redis.svc.cluster.local"
      port: 6379
      password: "<PASSWORD>"
    scylla:
      nodes:
	- <SCYLLA IP 1>
	- <SCYLLA IP 2>
	- <SCYLLA IP 3>
      replication: 3
      auth:
        username: "thorium"
        password: "<PASSWORD>"
    elastic:
      node: "https://elastic-es-http.elastic-system.svc.cluster.local:9200"
      username: "thorium"
      password: "<PASSWORD>"
      results: "results"
  registry_auth:
    <REGISTRY.DOMAIN: <base64 USERNAME:PASSWORD>
    <REGISTRY2.DOMAIN: <base64 USERNAME:PASSWORD>
