apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest 
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data
          volumeMounts:
            - mountPath: /data
              name: minio-data
          env:
            - name: MINIO_ACCESS_KEY
              value: "INSECURE_DEV_MINIO_ACCESS_KEY"
            - name: MINIO_SECRET_KEY
              value: "INSECURE_DEV_MINIO_SECRET_KEY"
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        storageClassName: csi-hostpath-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
---

apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: minio-web
    protocol: TCP
  type: ClusterIP
