apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: conf
  files:
  - redis.conf
resources:
- namespace.yml
- deployment.yml
- pvc.yml
- service.yml
namespace: redis
