apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistent-storage-claim
spec:
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 16Gi
  accessModes:
  - ReadWriteOnce
