name: Import public repos into monorepo (subtree → main)

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: monorepo-import
  cancel-in-progress: false

env:
  # URL:DEST (split on the LAST colon)
  REPOS: |

    https://github.com/fedemenstahgriltrocast-max/agents-starter.git:apps/agents-starter
    https://github.com/fedemenstahgriltrocast-max/vllm.git:apps/vllm
    https://github.com/fedemenstahgriltrocast-max/ollama.git:apps/ollama
    https://github.com/fedemenstahgriltrocast-max/LibreChat.git:apps/LibreChat
    https://github.com/fedemenstahgriltrocast-max/github-mcp-server.git:apps/github-mcp-server
    https://github.com/fedemenstahgriltrocast-max/came-llama.git:apps/came-llama
    https://github.com/fedemenstahgriltrocast-max/camello-purple.git:apps/camello-purple
    https://github.com/fedemenstahgriltrocast-max/PurpleLlama.git:apps/PurpleLlama
    https://github.com/fedemenstahgriltrocast-max/murmur.git:apps/murmur
    https://github.com/fedemenstahgriltrocast-max/ollama-ui.git:apps/ollama-ui
    https://github.com/fedemenstahgriltrocast-max/solution-ai-barista.git:apps/solution-ai-barista
    https://github.com/fedemenstahgriltrocast-max/TinyLLM.git:apps/TinyLLM
    https://github.com/fedemenstahgriltrocast-max/LangBot.git:apps/LangBot
    https://github.com/fedemenstahgriltrocast-max/thorium-eter.git:apps/thorium-eter
    https://github.com/fedemenstahgriltrocast-max/TinyLlama.git:apps/TinyLlama
  
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (default branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "monorepo-import-bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Ensure 'main' exists and checkout 'main'
        id: ensure_main
        shell: bash
        run: |
          set -euo pipefail
          if git ls-remote --exit-code --heads origin main >/dev/null 2>&1; then
            echo "main exists on origin."
          else
            echo "main does not exist; creating from current HEAD."
            # Create/force local main from current HEAD and push
            git checkout -B main
            git push -u origin main
          fi
          git checkout main

      - name: Import each repo via subtree (public) into main
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n'
          for raw in $REPOS; do
            # Trim whitespace/CRLF
            line="$(echo "$raw" | tr -d '\r' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            [ -z "$line" ] && continue

            # Split on the LAST colon: URL:DEST
            url="${line%:*}"
            dest="${line##*:}"
            if [[ -z "$url" || -z "$dest" ]]; then
              echo "Skipping malformed line: $line"
              continue
            fi

            repo_name="${url##*/}"; repo_name="${repo_name%.git}"
            alias="src_${repo_name}"

            echo "----"
            echo "Importing ${url} → ${dest}"

            git remote remove "$alias" >/dev/null 2>&1 || true
            git remote add "$alias" "$url"
            git fetch --prune "$alias"

            # Detect default branch of source (fallback: main)
            default_branch="$(git remote show "$alias" | sed -n 's/.*HEAD branch: //p')"
            if [ -z "$default_branch" ]; then default_branch="main"; fi
            echo "Default branch for $repo_name: $default_branch"

            # Decide ADD vs PULL using git's tree (not filesystem)
            if git ls-tree -d --name-only HEAD "$dest" 2>/dev/null | grep -qx "$dest"; then
              echo "Tracked at HEAD → subtree PULL update..."
              git subtree pull --prefix="$dest" "$alias" "$default_branch" -m "Update ${repo_name} into ${dest}"
            else
              echo "Not tracked yet → subtree ADD import..."
              # Remove stray empty dir if any (from prior failure)
              if [ -d "$dest" ]; then rmdir "$dest" 2>/dev/null || true; fi
              git subtree add --prefix="$dest" "$alias" "$default_branch" -m "Import ${repo_name} into ${dest}"
            fi

            git remote remove "$alias" || true
          done

          git push origin main
