version: 0.1
log:
    level: debug
http:
    addr: 0.0.0.0:5000
    secret: <SECRET> 
    relativeurls: true
storage:
    s3:
        accesskey: <S3 Access Key> 
        secretkey: <S3 Secret Key> 
        region: none
        bucket: docker-registry
        regionendpoint: <S3 endpoint> 
        skipverify: true
